In [1]:
import torch

In [2]:
x = torch.tensor([3.0])

In [3]:
y = torch.tensor([2.0])

In [5]:
x + y, x * y, x / y, x ** y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [6]:
x = torch.arange(4)

In [7]:
x

tensor([0, 1, 2, 3])

In [8]:
x[3]

tensor(3)

In [9]:
len(x)

4

In [10]:
x.shape

torch.Size([4])

In [11]:
A = torch.arange(20).reshape(5, 4)

In [12]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [13]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [15]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])

In [16]:
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [17]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [18]:
X = torch.arange(24).reshape(2, 3, 4)

In [19]:
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [20]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)

In [21]:
B = A.clone()

In [22]:
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [23]:
 x = torch.arange(4, dtype=torch.float32)

In [24]:
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [26]:
A = torch.arange(20*2).reshape(2, 5, 4)
A.shape, A.sum()

(torch.Size([2, 5, 4]), tensor(780))

In [28]:
u = torch.tensor([3.0, -4.0])

In [29]:
torch.norm(u)

tensor(5.)

In [30]:
torch.abs(u).sum()

tensor(7.)

In [31]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

In [32]:
a = torch.ones((2, 5, 4))

In [33]:
a.shape

torch.Size([2, 5, 4])

In [35]:
a.sum(axis=1).shape

torch.Size([2, 4])

In [36]:
a.sum(axis=1)

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [37]:
a.sum(axis=0).shape

torch.Size([5, 4])

In [38]:
a.sum(axis=[0, 2]).shape

torch.Size([5])

In [40]:
a.sum(axis=1, keepdims=True)

tensor([[[5., 5., 5., 5.]],

        [[5., 5., 5., 5.]]])

In [41]:
a.sum(axis=1, keepdims=True).shape

torch.Size([2, 1, 4])

In [43]:
a.sum(axis=[0, 2], keepdims=True).shape

torch.Size([1, 5, 1])